anki/cozmo-python-sdk

- Makefile
@gwatts @msintov, please review.
> COZMO-6039-remove-sdk-from-vagrant-bundle

- src/cozmo/run.py
Prevent Android warning when iOS device is connected and running Cozmo.
> Prevent Android warning when iOS device is connected and running Cozmo

- docs/source/adb.rst
- docs/source/getstarted.rst
- docs/source/index.rst
- docs/source/initial.rst
- docs/source/install-linux.rst
- docs/source/install-macos.rst
- docs/source/install-osx.rst
- docs/source/install-windows.rst
- docs/source/install.rst
broke out adb and install sections into their own pages
> broke out pages

- src/cozmo/faces.py
- src/cozmo/objects.py
- src/cozmo/robot.py
COZMO-6231 Added docstrings for the robot properties that were missing them
> COZMO-6231-Added docstrings for the robot properties that were missing them

- examples/alarm_clock.py
- examples/annotate.py
- examples/cozmo_face_image.py
- examples/flask_helpers.py
- examples/remote_control_cozmo.py
- examples/twitter/twitter_helpers.py
- src/cozmo/behavior.py
Changed all the pip install and pip3 install prints and errors to do:
pip3 install --user
> COZMO-6448 Suggest pip3 install --user for all pip installs

- src/cozmo/robot.py
- Update SayTextVoiceStyle names
- Add fitToDuration parameter to clad message constructor. We are not currently supporting this feature in the sdk.
> Update SayText CLAD Message

- docs/source/getstarted.rst
- docs/source/tutorial-beginner.rst
Links for free source code editors for Mac/Windows/Linux
> Same links available in getstarted.rst but added here for thoroughness

- examples/remote_control_cozmo.py
Now supports (toggle-able) debug annotations
Doesn't force Cozmo off the charger at start
Tidied up the bad_anim_names now that most of those animations no longer exist.
> COZMO-6858 RemoteControl example improvements

- examples/cube_stack.py
Recently added action.failed method was renamed to action.has_failed
> Fix failed vs has_failed syntax error

- examples/desk_security_guard.py
Replaced some hardcoded animation names (where those animations no longer exist) with triggers as that's more robust for future changes
> COZMO-7700 Update desk security guard anims

- docs/source/tutorial-beginner.rst
- src/cozmo/robot.py
Clarified API docs for turn direction
Changed turn example documentation to better match the turn behavior
Fixed a couple of typos where code didn't match what was suggested to type
Fixed a number of layout issues (indentation and closing fixed automatically by editor)
> COZMO-7011 Fixed some errors / inaccuracies in turn docs

- src/cozmo/annotate.py
- src/cozmo/faces.py
- src/cozmo/pets.py
- src/cozmo/robot.py
Now that facial features are available, store them in the face and draw them in the debug annotations
Allow facial expression estimation to be enabled and tracked, and draw it on annotations when relevant
Fix PET_TYPE_UNKOWN typo to PET_TYPE_UNKNOWN
> COZMO-7699 Show Facial Features

- src/cozmo/robot.py
Remove Robot._reset_behavior_state() - replace usage with more correct Robot._stop_behavior(), and move that to the private function section of robot.py
> COZMO-7776	Remove _reset / _stop behavior code duplication

- src/cozmo/action.py
Clad changes made by https://github.com/anki/cozmo-one/pull/2881
Can search for "clad/src" on the "Files changed" tab to see what changed
> Support ActionResult changes

- examples/cozmo_face_mirror.py
Simple example program that displays Cozmo's camera feed, flipped horizontally, back on his face to give the effect that he's a mirror.
> COZMO-7769 Add Face Mirror Example

- src/cozmo/action.py
- src/cozmo/run.py
*  Updating some clad messages
*  Exposing the TCPConnector class for use to connect to webots
> COZMO-7650 SDK webots test

- examples/tutorials/02_cozmo_face/03_alarm_clock.py
Now that the face image is an action, alarm_clock was triggering an exception when playing the alarm animation as the face image was pending - fixed by explicitly aborting pending actions first.
> Update alarm_clock for face action changes

- src/cozmo/robot.py
Changes to clad messaging for enabling/disabling reactions
> Update enableAllReactionTriggers to AllTriggersConsidered struct

- examples/if_this_then_that/ifttt_gmail.py
- examples/if_this_then_that/ifttt_sports.py
- examples/if_this_then_that/ifttt_sports_flask.py
- examples/if_this_then_that/ifttt_stocks.py
- examples/tutorials/01_basics/08_animation.py
ID_pokedB anim was renamed in the 1.5 app
For future proofing references to it have been changed to use a trigger rather than rely on the exact anim name
> COZMO-11126 Remove ID_pokedB anim usage

- docs/source/adb.rst
Modified adb setup instructions
https://github.com/anki/cozmo-python-sdk/issues/100
> updated adb instuctions

- examples/if_this_then_that/ifttt_gmail.py
- examples/if_this_then_that/ifttt_sports.py
- examples/if_this_then_that/ifttt_stocks.py
Tested with aiohttp versions 1.0.5 and 2.0.7
> COZMO-11655 Update IFTTT aiohttp scripts to work with latest aiohttp version

- examples/tutorials/04_cubes_and_objects/06_pickup_furthest.py
This should make this tutorial more consistent with nearby tutorials.
> modified the pickup_furthest tutorial to look around, and pickup the object with retries.

- src/cozmo/robot.py
Clarify the description for `is_localized` to emphasize that `localized` means position is known with respect to a cube.
> Clarify the description for `is_localized` method

- src/cozmo/camera.py
- src/cozmo/robot.py
fixed comment explaining Angle
> COZMO-12360 fix camera_config and set_head_angle docstring

- Makefile
- examples/apps/quiz_questions.json
- examples/apps/quizmaster_cozmo.py
- src/cozmo/objects.py
- src/cozmo/run.py
- src/cozmo/world.py
Add an example quiz program using the cubes as buzzers
Add Json files to the examples zip (as quiz uses one)
Updated run.py to more cleanly handle exit of async programs when the user presses CTRL-C to keyboard interrupt
Added objects.LightCubeIDs helper list of all 3 cube IDs
> COZMO-12173 Quizmaster Cozmo example

- docs/source/vagrant.rst
vagrant instructions were missing that "vagrant ssh" should be run after "vagrant up"
> COZMO-12820 doc update

- examples/apps/color_finder.py
- src/cozmo/camera.py
- src/cozmo/util.py
The ColorFinder app contains:
**ColorFinder** class, which contains the annotation code, handling cube taps, sending the camera view approximation to a BlobDetector, and managing the driving/head-tilting/rotating actions.
**color_ranges**, which defines colors based on their bounded three-dimensional regions in RGB space.
**color_distance_sq**, which computes the squared distance from a color point to a color range.
**color_balance**, which applies a "Gray World" algorithm to balance the color distribution in an image.
**BlobDetector** class, which takes the matrix of approximated colors from ColorFinder and constructs a dictionary of the contiguous regions of color.  It also contains a method to find the approximate center of the largest blobs so that Cozmo can turn his focus towards the …
> COZMO-12630-ColorFinder app

- examples/apps/color_finder.py
"swatting" feature brings the lift down when tennis ball is close to Cozmo (really when the color_to_find takes up a large portion of the screen), to simulate Cozmo swatting at the thing
> color-finder update: uncommented lookaround state, added "swatting"

- setup.py
- src/cozmo/run.py
- src/cozmo/util.py
- tox.ini
- vagrant/setup-vm.sh
Added PyOpenGL dependencies to tox, and fixed indentation issue it reported.
> Standardized casing of PyOpenGL pip package names across all files.

- setup.py
Document optional requirements for 3D viewer (for PyPi documentation of the next build)
> Document optional requirements for 3D viewer

- examples/apps/cli.py
- examples/apps/remote_control_cozmo.py
- examples/lib/flask_helpers.py
- cli support interface
- Improved the performance of remote-control-cozmo app
> Cli and remote control update

- src/cozmo/annotate.py
- src/cozmo/util.py
Document the properties / attributes of util.ImageBox (included adding new properties to more cleanly access the edges)
Added a "center" helper property that returns the x,y of the center of the box
> Document the properties / attributes of util.ImageBox

- docs/source/install-linux.rst
- src/cozmo/robot.py
Fix Ubuntu 14.04 install instructions as per https://forums.anki.com/t/linux-install-notes/55/9?u=mwesley (needed a priority specifying, and to use python3.5 instead of specifically trying to use python3.5.1
Fix docstrings for start_behavior and run_timed_behavior - the class type was missing a closing quote
> Minor documentation fixes

- examples/apps/remote_control_cozmo.py
- examples/tutorials/01_basics/08_animation.py
- src/cozmo/audio.py
- src/cozmo/robot.py
id_poked_giggle was renamed to anim_poked_giggle
Added audio events for MusicFunLoop and SfxPuttHoleSuccess
Added speed, accel, angle_tolerance and is_absolute parameters to turn_in_place
> Changes for the 2.2 app release

- src/cozmo/event.py
The “majorWin” animation has been renamed to “anim_majorwin" per COZMO-8868
> COZMO-8868 Renamed the “majorWin” animation

- docs/source/adb.rst
- docs/source/api.rst
- docs/source/downloads.rst
- docs/source/getstarted.rst
- docs/source/index.rst
- docs/source/initial.rst
- docs/source/install-linux.rst
- docs/source/install-macos.rst
- docs/source/install-windows.rst
- docs/source/sdk-versions.rst
- docs/source/tutorial-advanced.rst
- docs/source/vagrant.rst
- examples/tutorials/01_basics/10_play_sound.py
- examples/tutorials/01_basics/11_play_song.py
- examples/tutorials/01_basics/12_random_animation.py
- src/cozmo/anim.py
- src/cozmo/audio.py
- src/cozmo/objects.py
- src/cozmo/robot.py
- src/cozmo/song.py
- properly cast floats in angle util
- fix 02_cozmo_face/01_cozmo_face_image to work from anywhere
- cubes invalidate pose when moved
- exposed song functionality; added play_song tutorial
- added random_animation tutorial to demonstrate polling supported animations
- called out play_audio tutorial in audio.py documentation, updated tutorial to demonstrate starting & stopping sounds
- documentation updates
> 1.4.0 release merge private fork
