anki/cozmo-python-sdk

- src/cozmo/robot.py
Fix robotId vs robotID typo in Robot.abort_all_actions that made this function uncallable
> Fix typo in abort_all_actions

- docs/source/api.rst
- examples/alarm_clock.py
- examples/cozmo_face_image.py
- src/cozmo/__init__.py
- src/cozmo/oled_face.py
- src/cozmo/robot.py
Correct code references from LCD to OLED:
* rename cozmo.lcd_face to cozmo.oled_face
* rename robot.display_lcd_face_image to robot.display_oled_face_image
* change LCD to OLED in comments
This is a (hopefully unusual) backwards-incompatible change.
> Correct code references from LCD to OLED

- src/cozmo/version.py
Only production builds should be pinned to an explicit version of
comzmoclad; performing a build from a checkout should use whichever
version is installed (though subject to the usual runtime checks).
> repo builds should not depend on explicit cozmoclad

- src/cozmo/faces.py
- src/cozmo/robot.py
Doing Face.name_face with the default sequence leaves an idle animation looping on Cozmo, so:
a) Allow that to be skipped (via passing in play_anim=False)
b) Allow idle animation to be set/cleared afterwards
Fixed a couple of existing issues with EnrollNamedFace docstrings being incorrectly generated
> Support skipping and clearing idle animation after face enrollment

- examples/drive_to_charger_test.py
- examples/go_to_object_test.py
- src/cozmo/objects.py
- src/cozmo/robot.py
- src/cozmo/world.py
Added charger factory and object
Added docsstrings for factory objects in world.py
Send RequestAvailableObjects on robot initialize - and handle AvailableObjects message that is returned, this gives us info on connected cubes at the start instead of having to wait to visually see them.
Upgraded "Tap event received for unknown object ID" back to a warning as we should always know about that cube now
Fixed robot.py factory docstrings (they were missing a colon before class)
Made robot keep track of it's origin_id for poses
Added GoToObject support for driving to within X mm of a cube or charger
Added go_to_object_test.py example that shows usage of GoToObject action for finding a cube and driving up to it
Added drive_to_charger_test.py example that shows usage of accessing the charger and …
> Added Charger object support to SDK

- src/cozmo/anim.py
- src/cozmo/conn.py
Replaced the ambiguous "UI connected" message with something more
meaningful and record the SDK version along with the version of
cozmoclad and the connected build version.
Lower the animations loaded count to a debug as it's generally not a
useful number.
> Log version numbers at startup

- src/cozmo/conn.py
On CLAD match but version mismatch, check if the major.minor still match (i.e. this is just a patch version change) and if so allow it, but warn user that they should upgrade app or SDK as appropriate.
Added link to the downloads and suggestion that they should download the latest examples when upgrading the SDK.
> Allow SDK connection if CLAD and major.minor version matches

- src/cozmo/conn.py
Demote INVALID ROBOT_ID SEEN warning to a debug - the case is handled, the ID is currently meaningless, and we'd need to update engine to change the ID (I suspect it's passing in a serial number instead of the engine ID)
> COZMO-6857 Suppress INVALID ROBOT_ID warning 

- examples/alarm_clock.py
- src/cozmo/robot.py
Print out how to set the alarm time (if none was provided)
Print out how to press CTRL-C to quit
Upped default backup_onto_charger timeout to 3 from 2 seconds (alarm clock was using 3, as there were occasional cases that it'd take too close to 2 seconds for comfort)
> Use robot.perform_off_charger now that we've moved that into robot

- examples/cube_stack.py
- src/cozmo/action.py
- src/cozmo/objects.py
- src/cozmo/world.py
The "Wait for observed" functions (listed below) now all take in "include_already_visible" (defaulted to true) which includes already visible objects (as these do not create observation events, they would otherwise be ignored), you can obtain the old behavior by passing in include_already_visible=False:
Actions expose more info on success / failure
cube_stack example now more reliable, and includes information on action failure
wait_until_observe_num_objects
wait_for_observed_charger
wait_for_observed_face
wait_for_observed_light_cube
> COZMO-6586 Include already visible objects/faces

- docs/source/getstarted.rst
- docs/source/tutorial-beginner.rst
(patch supplied by Stuart)
In the getting started and tutorial documents, we were saying "iOS and
Linux" when we meant "macOS and Linux"
> Correct typo : Replace iOS with macOS where needed

- examples/remote_control_cozmo.py
- src/cozmo/robot.py
- src/cozmo/util.py
Pull gyro and accelerometer IMU data out of RobotState message and store
Added Vector3 class for storing the above (basically renamed util.Position class, and made Position just a subclass of that)
Slightly more info in robot.pose property docstring
Added (optional) RobotState display annotation to remote_control example for verifying the IMU data
Fixed a couple of small bugs in remote control - updated default animations (2 were removed from 1.1.0), and removed the wait_for_completed on the drive_off_charger_contacts action (it isn't required, and would freeze the camera feed for a second)
Reordered display of remote control key mappings from 0..9 to 1..9,0 to match the layout of the keys on a keyboard.
> COZMO-4894 Expose Robot IMU data

- examples/remote_control_cozmo.py
- src/cozmo/robot.py
Add robot.set_head_light method to turn IR headlight on and off
Added keyboard and button mappings to turn IR light on and off in the remote_control_cozmo example program
> COZMO-7518 Add IR Headlight control

- examples/remote_control_cozmo.py
- src/cozmo/behavior.py
- src/cozmo/robot.py
Provided access to enable and disable Freeplay mode from SDK - this lets you leave Cozmo running autonomously, similar to the main Cozmo app, whilst still having the SDK running.
Added button and key for enabling and disabling Freeplay mode from the remote control example program.
> COZMO-6276 Allow Freeplay mode in SDK

- src/cozmo/conn.py
- src/cozmo/objects.py
- src/cozmo/robot.py
Request the available objects earlier, before requesting the available animations - this ensures we have received the available objects before we mark the robot as ready, because we already wait on the animation list to arrive. (Note: adding an additional check to wait for available objects wouldn't be possible without an app change, because there's no guarantee of any message in the case that all cubes and charger are disconnected).
> COZMO-7567 Get Available Objects before Robot Ready

- src/cozmo/robot.py
Since the 1.1.0 version of the app the maxTurnAngle_rad value must be > 0 to allow Cozmo to turn whilst performing TurnTowardsFace, without this Cozmo will only look up and down.
> COZMO-7703 Fix TurnTowardsFace turning angle

- src/cozmo/conn.py
Minor app version changes are often just hotfixes to the app that don't touch CLAD or require an SDK update - therefore warning on them, or suggesting that the user should update to an SDK that might not exist, makes no sense.
> COZMO-7768 Dont Warn on Minor App version mismatch

- docs/source/adb.rst
Update Windows adb instructions to account for the Android SDK Tools Setup Wizard no longer appearing in the command line tools download.
Mark - if you could, please try these instructions out on your computer. Thanks!
> Update Windows adb instructions

- examples/tutorials/01_basics/07_backpack_lights.py
- src/cozmo/objects.py
- src/cozmo/robot.py
Added note on backpack lights regarding left/right being red LED only
Added set_center_backpack_lights function that forces left/right LEDs to off, which is the more likely use-case.
Added warning to play_anim regarding how we recommend play_anim_trigger instead as individual animations may be renamed or removed in future app versions.
> Documented what each of the 5 backpack lights refers to.

- examples/tutorials/06_actions/01_parallel_actions.py
- src/cozmo/action.py
- src/cozmo/robot.py
Adding in_parallel parameter for all actions, this tells engine to run in parallel (and not clear current actions), and also prevents the SDK from raising an exception if there were pending actions in that case.
OLED face image is now an sent as a parallel action, with previous face actions automatically aborted each time
Aborted actions are immediately not considered in-progress (no longer have to wait a frame for engine to return the cancelled message before starting another action)
Added 06_actions/01_parallel_actions.py example to demonstrate the above.
> COZMO-6362 Parallel Action Support

- examples/tutorials/04_cubes_and_objects/08_drive_to_charger_test.py
- src/cozmo/objects.py
- src/cozmo/util.py
When receiving object info on connection - poses where PoseState is unknown are always invalid and should just be ignored.
Added support to Util.Pose for tracking validity.
Updated 08_drive_to_charger_test to show usage.
> COZMO-7694 Check validity of poses

- Makefile
Also emove real target phony dependencies to ensure targets are only built
when necessary
> Update Makefile for new example layout

- src/cozmo/faces.py
Remove EnrollNamedFace action and factory, as there is no longer a matching Action in Engine or CLAD
Commented out Face.name_face() method for now - it ultimately needs replacing with usage of the new face-naming behavior
> COZMO-8803 Remove EnrollNamedFace action

- docs/source/adb.rst
Simplify the Windows adb install instructions by using a new link that downloads platform-tools directly instead of using the Android Studio command line tools download and installer. Google promises to keep the latest platform-tools available at the new link.
With the new instructions the user no longer needs to run the android/SDK Manager installer tool, and because of this, the user also no longer needs to install Java.
> Improve Windows adb instructions

- docs/source/getstarted.rst
Issue reported to Kaiser by a Windows SDK user.
> Update getstarted: fix backslash on Win

- docs/source/adb.rst
Linux add instructions now use the platform-tools-latest-linux.zip file download. With this change, the Linux instructions are now following the same steps as Windows in that they now avoid the Android Studio command line tools download, Java install and Android SDK Manager.
> Update Linux adb instructions

- src/cozmo/world.py
Renaming `Custom_Fixed` object type to `CustomFixedObstacle` (mirroring Cozmo Engine change)
> Renaming `Custom_Fixed` object type to `CustomFixedObstacle`

- src/cozmo/tkview.py
There was a race condition where if >1 image_event occurred before _draw_frame was called, the scale wouldn’t be applied to a rendered image and the window would never scale.
This change ensures that we keep applying the scale (instead of fitting to the window) until an image has been displayed (which should allow the scale to resize the window)
> COZMO-9860 Fix occasional failure to scale TkView window at start

- src/cozmo/objects.py
Unfortunately the SDK assumption that Engine would never change an Object ID is invalid
Hopefully a future Engine update will allow it to be more reliable, but for the timbering we handle the ID change, and just log a warning to help anyone debug any related issue they might see (if e.g. they were storing the IDs somewhere).
> COZMO-9679 Warn gracefully on object ID changes

- src/cozmo/run.py
Docstring for use_viewer was a duplicate of the force_viewer_on_top documentation.
> COZMO-8013 Correct use_viewer docs for run_program

- src/cozmo/action.py
- src/cozmo/anim.py
Aborting an action that just completed (but didn’t yet receive the event to update from running to complete) no longer results in an exception but now gracefully does nothing.
AnimationTrigger class now correctly caches and returns completed event in the case of WaitForCompleted() being called when already complete
Animation class now behaves like AnimationTrigger in dispatching EvtAnimationCompleted on completion instead of base Action’s event
> COZMO-9686 Fix rare exception from aborting a just-completed action

- examples/tutorials/03_vision/04_exposure.py
- src/cozmo/annotate.py
- src/cozmo/conn.py
- src/cozmo/robot.py
- src/cozmo/util.py
Added a Vector2 helper class (like Vector3, but without the z component)
Added a CameraConfig class to robot for keeping track of camera properties and settings
On connection SDK programs now immediately receive a number of per-robot settings, includes serial number and camera calibration.
Camera Exposure can now be override manually.
Current exposure and gain values are streamed back to SDK from Engine as they’re updated.
Added a tutorial example that shows exposure settings in action
Expanded annotation system slightly to make it support outlined/shadowed text, and line-spacing overrides.
> COZMO-9128 Camera properties and exposure controls

- examples/tutorials/04_cubes_and_objects/05_cube_stack.py
- src/cozmo/action.py
Wrapped the ActionResult from CLAD with a documented Python class to more clearly explain the meaning of each result.
Corrected the action documentation to account for in_parallel usage, and how ActionResult relates to that.
Updated cube_stack example to print the result for failed pickup or place actions.
> COZMO-7787 Expose the result of an Action more clearly.

- src/cozmo/world.py
A bug was introduced on the app-side where the EnableLightStates(enable=False) message (which is automatically sent to disable the cube lights on entering SDK mode and at the end of every SDK program) no longer turns off the lights as part of changing the states. This will be resolved for the 1.3 app release, but in the meantime we’ll automatically turn the lights off on cubes when SDK first connects to them each time to avoid cube lights persisting across multiple SDK program runs.
> COZMO-9810 Turn off cube lights on SDK connection

- src/cozmo/action.py
Added Action result to the repr if the action failed to give more info on what failed.
Wrapped failure_reason in quotes as the values have spaces in so it's hard to read otherwise.
> COZMO-7787 Include Result in Action string representation

- docs/source/adb.rst
- docs/source/getstarted.rst
- docs/source/install-macos.rst
- docs/source/install-windows.rst
Embedded the 2 mac videos in the macOS page, and the 2 Windows ones to the Windows installation page.
Embedded the basic walkthrough in the get started section
Fixed warning from adb.rst generation (you can’t have 2 links with the same name unless you make them anonymous with a double trailing underscore instead of a single one).
> COZMO-9710 Add Youtube installation videos into the documentation

- examples/if_this_then_that/ifttt_gmail.py
- examples/if_this_then_that/ifttt_sports.py
- examples/if_this_then_that/ifttt_stocks.py
- examples/lib/flask_helpers.py
- src/cozmo/action.py
- src/cozmo/camera.py
- src/cozmo/objects.py
- src/cozmo/robot.py
- src/cozmo/run.py
- src/cozmo/world.py
logger.warn is deprecated, replaced all instances with logger.warning
Flask’s send_file complains on 0.11.0 if add_etags is used without a filename, and from 0.12.0 on ignores it, so just set add_etags=False as we don’t require them and there’s no way to specify the filename _and_ a bytesIO object in a way that will use the filename for the tag.
> COZMO-10283 Fix usage of deprecated methods from SDK

- src/cozmo/lights.py
Cube lights ignore the alpha component, so make it clear from the SDK API that only RGB values matter by removing RGBA setters.
> COZMO-10301 Remove alpha component from Cube lights

- src/cozmo/conn.py
Make the version mismatch error stand-out from the rest of the Python text by adding more spacing, new lines to separate it from the long prepended text on each log message, and generally improving the formatting.
> COZMO-10293 Make Version Mismatch error stand out more

- examples/tutorials/03_vision/04_exposure.py
- src/cozmo/camera.py
- src/cozmo/robot.py
- src/cozmo/run.py
Moved CameraConfig from roboy.py into camera.py
Deprecated robot.camera_config, robot.enable_auto_exposure and robot.set_manual_exposure
Updated 04_exposure example to match, and made it run once in grayscale and once in color.
Fixed a couple of small docstring issues in robot.py whilst getting the camera doc changes to work.
> COZMO-10267 Moved CameraConfig into Camera

- src/cozmo/robot.py
Driving off with in_paralelel=True means that it’s now possible to have an existing action (e.g a face action) in progress whilst Cozmo drives off the charger (previously this would force you to first abort any pending actions).
Fixed on charger docstring fi vs if typo, and other instance next to it.
> COZMO-10390 PerformOffCharger drive-off action done in_parallel

- src/cozmo/behavior.py
- src/cozmo/faces.py
- src/cozmo/robot.py
Face.name_face was removed in a recent update as the Action to perform this internally was removed. This has been replaced with a Behavior, so the method has been revived to use that.
To enable the use of a Behavior in a way closer to an Action, the behavior code has been updated to track changes in behavior to allow to wait for a behavior to complete, and also catch when a behavior never starts (e.g. if it is not considered runnable if various engine preconditions are not met).
> COZMO-8803 Replace name_face Action with Behavior

- src/cozmo/faces.py
- src/cozmo/objects.py
- src/cozmo/robot.py
- src/cozmo/world.py
Removed EvtObjectAvailable reference (it no longer exists)
Replaced logger.warn with logger.warning
Added more detail to CustomObject and FixedCustomObject docstrings to show how to create/use them.
Fixed head vs lift typos in SetLiftHeight
Add type info for World.latest_image (helps Pycharm etc.)
Replaced warning in recv_msg_located_object_states with code to handle that case, as it happens frequently.
> COZMO-10798 Fix warnings in docs and code

- src/cozmo/world.py
Previous docstring and code was misleading, suggesting that 6 unique markers only required for a unique box, but currently this is required for any custom_box so made the check explicit on the Python side (otherwise there’s a more cryptic “Failed to define Custom Object” message.
> COZMO-10823 Document that custom_box requires 6 unique markers

- examples/tutorials/01_basics/09_cube_lights.py
- src/cozmo/objects.py
- src/cozmo/world.py
Removed spurious info from EvtObjectConnected
Keep track of LightCube.is_connected
Expanded docstring for “lamp” cube as some people think it looks like a heart.
Moved _recv_msg_object_connection_state to the correct class, and made sure the message gets to the cube
Added World.get_light_cube to make it cleaner to get a cube by ID and automatically handle the case where there was a part-initialized cube (no cube is connected to the robot).
Added cube_lights example that sets cubes to red, green, blue without having to have been seen.
> COZMO-10809 Cube connection and color example

- src/cozmo/action.py
Laser work added new BAD_MESSAGE_TAG error code. @alchaussee  pointed out it needed to be listed here in the SDK as well.
> Add bad message tag

- src/cozmo/action.py
This change is to support the removal of an ActionResult which was done in https://github.com/anki/cozmo-one/pull/4136 to improve action retry behavior.
> COZMO-11024: Align actions not succeeding as often as expected

- src/cozmo/action.py
Added new Action Result “INVALID_OFF_TREADS_STATE” for situations where the robot ends up in an invalid orientation while executing an action.
> COZMO-11731 Actions handling OffTreadsState on their own

- src/cozmo/robot.py
There was a typo in class cozmo.conn.CozmoConnectoin (should end "ion" not "oin") that meant you couldn't follow that particular link in the online documentation.
> Fix typo in documentation for Robot constructor

- src/cozmo/util.py
Even ignoring the likely performance gain of not calling sin/cos twice, this is also arguably clearer to read and more closely matches implementation in other languages.
> Removed duplicate sin + cos calls when rotating a pose

- src/cozmo/event.py
- src/cozmo/objects.py
- src/cozmo/robot.py
- src/cozmo/run.py
- src/cozmo/tkview.py
- src/cozmo/world.py
After reducing down the pylint pass to avoid spamming style-type errors, there were a few remaining things that I wanted either to fix or locally suppress
> COZMO-12298 clean up sdk for lint

- src/cozmo/run.py
Creating a new loop for every call to _connect_sync breaks the default
connector instance, which maintains a connection to usbmuxd using the
loop first available to it.  This prevents subsequent calls to connect
from succeeding for synchronous functions.
Instead allocate a loop for synchronous code up front and re-use that
for any subsequent sync calls.
Simple test that will fail prior to this update:
```python
import sys
import cozmo
def run(sdk_conn):
'''The run method runs once Cozmo is connected.'''
robot = sdk_conn.wait_for_robot()
if __name__ == '__main__':
cozmo.setup_basic_logging()
cozmo.connect(run)
cozmo.connect(run)
```
> COZMO-7331 Ensure sync connect calls use same loop

- src/cozmo/camera.py
change enable_exposure to enable_auto_exposure in camera.py
> fix-camera-exposure-example variable name fix

- src/cozmo/annotate.py
- src/cozmo/opengl.py
- src/cozmo/world.py
- vagrant/setup-vm.sh
Catch some errors specific to old/missing GLUT version on Windows
Fix error if Image and ImageDraw were not imported form PIL
Add PyOpenGL and freeglut to Vagrant install
> Handle OpenGL errors on Windows

- src/cozmo/opengl.py
math.tau was only introduced in Python 3.6
> Use (2.0 * math.pi) instead of math.tau

- docs/source/downloads.rst
- docs/source/index.rst
- vagrant/Vagrantfile
boxcutter no longer host boxes, and nobody seems to host a desktop box anymore so switched to an available server box.
Removed vagrant from documentation tabs, and removed the links from the download - the underlying files and the vagrant.html page still exist, so if anyone really needs it or was relying on it they can find it, but it's no longer user-facing so new users won't be confused by it being there (especially now that it's a non-desktop Linux image, so is less user-friendly).
> Switch the box used for Vagrant as old one no longer hosted

- docs/source/sdk-versions.rst
- src/cozmo/clad_protocol.py
- src/cozmo/conn.py
- src/cozmo/exceptions.py
- src/cozmo/run.py
SDKVersionMismatch can now be caught by client code, if they wish to handle it separately.
SDKVersionMismatch exception now includes SDK version along with required and actual App versions.
After detecting the version mismatch, any remaining messages on the connection are ignored (to avoid throwing exceptions when they fail to unpack)
If no valid device connection is found, and an SDKVersionMismatch was detected on any device, then that SDKVersionMismatch exception is returned instead of a general "no devices found" exception.
> Surface SDK version errors more cleanly

- src/cozmo/robot.py
The needs levels dictate how much Cozmo feels in need of repair, feeding, or playing with and they affect the animations and behavior - e.g. when Cozmo is feeling needy he'll appear to be sad, or damaged, etc.
> Add set_needs_levels method to override Cozmo's current levels

- src/cozmo/robot.py
Add an enable_freeplay_cube_lights method to Robot to allow users to enable the freeplay cube lights mode when in the SDK (by default the SDK always disables it because it overrides any other calls to set the cube light colors)
> Add robot.enable_freeplay_cube_lights method

- src/cozmo/run.py
I started building a REPL starting from the cli.py program in the sdk examples.
I have the need to catch connexion error to display some message in a more frendly way than logs.
Here is a patch to enable this =)
> add a throw_error flag to run_program to throw error rather than exit

- docs/source/install-linux.rst
I also reordered the document to split Ubuntu 14.04 apart from 16.04 because virtualenv doesn't work with `pip install --user`.
> Update linux docs to use virtualenv
